/**
 * Runtime game state.
 *
 * Convention:
 *  - Seats are indexed 0..nPlayers-1 in clockwise order. activeSeat advances
 *    +1 mod nPlayers every turn.
 *  - Queues (files de monstres) are ordered head-first: index 0 is the head
 *    (côté héros), which is what takes hits and attacks.
 *  - Wound stacks are stored as arrays; newest wound is appended at the end.
 *    Healing removes from the END (most recent) per rules.
 *
 * State is mutated in-place by engine functions. The event log in `events`
 * is the audit trail and source of truth for replays. Callers should never
 * mutate state directly; they go through engine functions.
 */

import type { Boss, CarteChasse, Destin, Hero, Menace, Monstre } from './types.js';
import type { GameEvent } from './events.js';
import type { EffectsCatalog } from './effectTypes.js';
import type { ModifierRec } from './modifiers.js';

export type Result = 'running' | 'victory' | 'defeat';

export type Phase =
  | 'HERO_ACTION'
  | 'BOSS_SEQUENCE'
  | 'GAME_END';

/** Wound card: any card that inflicted damage and sits under the target. */
export interface Wound {
  /** Unique id per wound instance (generated by the engine). */
  woundId: string;
  /** Type of source that inflicted the wound. */
  source: 'chasse' | 'menace' | 'destin' | 'monstre' | 'boss';
  /** Original card id (e.g. "MAG_A04", "EPR_014", "MON_004"). */
  sourceCardId: string;
  /** Amount of 🩸 this wound card contributes. */
  degats: number;
}

/** A Monstre currently in play (live instance, not the catalog card). */
export interface MonsterInstance {
  instanceId: string;
  cardId: string; // e.g. "MON_003"
  wounds: Wound[];
}

/** A hero's full runtime state. */
export interface HeroRuntime {
  seatIdx: number;
  heroId: string;
  vieMax: number;
  wounds: Wound[];
  hand: CarteChasse[];
  objects: CarteChasse[]; // objets posés devant
  capaciteUsed: boolean;
  dead: boolean;
  queue: MonsterInstance[]; // files de monstres, head first
  /** One-shot flag: next Action played by this hero ignores its prerequis. */
  nextActionIgnoresPrereq?: boolean;
  /** One-shot flag: this hero can pose 1 extra Objet this turn (ROD_A04). */
  extraPoseAvailable?: boolean;
  /** Actions (ACTION_PLAY_ACTION) played by this hero this turn. */
  actionsPlayedThisTurn?: number;
  /** Chasse cards drawn by this hero this turn. */
  drawsThisTurn?: number;
  /** Boss Azhda (BOSS_007) actif : this hero can only draw this turn. */
  onlyDrawThisTurn?: boolean;
  /** One-shot flag (set by ROD_O02 renfort) : next attack that kills its
   *  monster target continues onto the new queue head. */
  chainAttackOnKill?: boolean;
}

export interface BossRuntime {
  bossId: string;
  vieMax: number;
  wounds: Wound[];
  defeated: boolean;
}

/** A draw/discard pair for a card type. */
export interface Pile<T> {
  draw: T[];
  discard: T[];
}

export interface GameState {
  seed: number | string;
  rngState: number;
  nPlayers: number;

  activeSeat: number;
  turn: number;
  phase: Phase;
  result: Result;

  heroes: HeroRuntime[];
  boss: BossRuntime;

  piles: {
    chasse: Pile<CarteChasse>;
    menace: Pile<Menace>;
    monstre: Pile<Monstre>;
    destin: Pile<Destin>;
  };

  /** Full event log. Written in order of resolution; also exportable as JSONL. */
  events: GameEvent[];

  /** Monotonic counters to generate unique ids. */
  counters: {
    wound: number;
    monsterInstance: number;
    event: number;
  };

  /** Safety: max number of turns before forcibly ending as defeat. */
  turnCap: number;

  /**
   * Read-only catalog of all design data. Attached at setup; engine functions
   * use it for id lookups (monster vie, card defs, etc.).
   * Not serializable directly (contains Maps) — replay builds a fresh state
   * from SETUP event + actions, so state serialization is not needed.
   */
  catalog: DesignCatalog;

  /**
   * Simulator-owned DSL effect annotations, keyed by card / capacity id.
   * A card present here is interpreted via runOps(); a card absent falls back
   * to J2 "raw degats" behaviour. Empty by default (effects.json optional).
   */
  effects: EffectsCatalog;

  /** Active persistent modifiers. See engine/modifiers.ts. */
  modifiers: ModifierRec[];

  /** Flag set during Menace resolution; op cancelMenace reads this. */
  menaceCancelled?: boolean;
  /** Flag set during Destin resolution; SOI_O03 reactive can set it. */
  destinCancelled?: boolean;
  /** Set true when any hero was healed this turn (read by SOI_O05). */
  healedThisTurn?: boolean;

  /** Per-turn bookkeeping for boss passifs. */
  perTurnDraws?: Record<number, number>;
  /** Set when the active hero damages the boss this turn (Akkoro passif). */
  activeDamagedBossThisTurn?: boolean;
  bossDamagedThisTurn?: boolean;

  /**
   * Per-seat policy references. Set by runGame()/runTurn() so effect
   * handlers can consult them (pickChoice, pickHeroTarget, ...). Empty by
   * default — effect handlers fall back to RNG.
   *
   * Imported lazily to avoid a cycle with ai/policy.ts.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  policies: any[];
}

// ---------------------------------------------------------------------------
// Design-data snapshot carried by the engine (immutable view of catalog).
// ---------------------------------------------------------------------------

export interface DesignCatalog {
  heroesById: Map<string, Hero>;
  bossById: Map<string, Boss>;
  chasseById: Map<string, CarteChasse>;
  monstreById: Map<string, Monstre>;
  menaceById: Map<string, Menace>;
  destinById: Map<string, Destin>;
}
